import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:riverpod_practice/Notifier&Notifier_Provider/using_autogenerated/counter_notifier.dart';

class CounterWithAuto extends ConsumerWidget {
  const CounterWithAuto({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final counter = ref.watch(counterNotifierProvider);

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(
          title: const Text("Notifier & NotifierProvider"),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Text(
                counter.toString(),
                style: const TextStyle(fontSize: 30),
              ),
              const SizedBox(
                height: 20,
              ),
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  ElevatedButton(
                      onPressed: () {
                        ref.read(counterNotifierProvider.notifier).increment();
                      },
                      child: const Text("+")),
                  const SizedBox(
                    width: 20,
                  ),
                  ElevatedButton(
                      onPressed: () {
                        ref.read(counterNotifierProvider.notifier).decrement();
                      },
                      child: const Text("-")),
                ],
              )
            ],
          ),
        ),
      ),
    );
  }
}
